### PR TITLE
Feature Enable social logins 158626073

### PR DESCRIPTION
**Pull request by victorjambo**
**What does this PR do?**
Enable social logins for users; Facebook, Twitter, Google

**Description of Task to be completed?**
This PR enables users to login using facebook, twitter and google. Initially user could not login with their pre-existing social media account.

**How should this be manually tested?**
User can try to login manually with their social media accounts
`http://localhost:8000/en/user/login`

**Any background context you want to provide?**
To test this feature on you local machine, ensure you have Facebook, Twitter and Google developer apps. Once apps have been created export `CLIENT KEY & CLIENT SECRET` as env variables.
Its important to run migrations for this feature to work 

**What are the relevant pivotal tracker stories?**
[#158626073](https://www.pivotaltracker.com/story/show/158626073)

**Screenshot**
screen shot 2018-07-25 at 11 03 13

### CODE REVIEW

**Comment by EinsteinNjoroge** [comment]
@victorjambo there are so many new dependencies in your requirements file, are they all necessary?

**Comment by victorjambo** [comment]
@EinsteinCarrey Initially I did a `pip freeze > requirements.txt` this pushed unwanted requirements. I have made necessary changes to include requirement required for this feature. That is, `social-auth-app-django==2.1.0` and `social-auth-core==1.7.0`

**Comment by brian-mecha** [comment]
LGTM. Good job👏🏽

**Comment by Michyjones** [comment]
Awesome work. I have tested the feature it is working perfect.

**Comment by cosmas28** [comment]
LGTM!!! Both Google and Twitter are working fine, I think we can test Facebook on Heroku because it does not accept HTTP. Well done

**Pull request merged**
